name: pr
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  IMAGE_NAME: ${{ github.event.repository.name }}
  VERSION: '1.0.1'
  SHA256: '62dfc2afb37c0124b755dbcee52e5af5cea2da372609cc83a8c2cbb62caf7598'

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Build container image
        run: |
          make docker
